### ISSUE TITLE
scatter_add

### ISSUE THREAD

**Issue by wangzeyu135798** [rusty1s/pytorch_scatter#174]
Hi:
   Recently, I meet a question.
   RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)
   How to solve this? My torch-scatter version is 2.0.5.

**Comment by rusty1s** [comment]
Where does this error occur? The `torch-scatter` API slightly changed with version 2, i.e. there is no more `fill_value` argument in later versions).

**Comment by wangzeyu135798** [comment]
Hi: &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
&nbsp;&nbsp; When I run this line, error occur.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rusty1s/pytorch_scatter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 凌晨0:20
收件人:&nbsp;"rusty1s/pytorch_scatter"<pytorch_scatter@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rusty1s/pytorch_scatter] scatter_add (#174)





 
Where does this error occur? The torch-scatter API slightly changed with version 2, i.e. there is no more fill_value argument in later versions.

**Comment by rusty1s** [comment]
Are you sure that line is causing this issue? There are not 6 arguments passed to the `scatter_add` call.

**Comment by wangzeyu135798** [comment]
File "/data/wangzeyu/code/pretrain-gnns-master/bio/model.py", line 54, in forward
    return self.propagate(edge_index=b, x=x, edge_attr=edge_embeddings, aggr='add')
  File "/data/wangzeyu/wangzeyu_torch/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 58, in propagate
    out = scatter_(aggr, out, edge_index[0], dim_size=size)
  File "/data/wangzeyu/wangzeyu_torch/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
    out = op(src, index, 0, None, dim_size, fill_value)
RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)
The self.propagate function is under class torch_geometric.nn.MessagePassing . The scatter_add() is under torch_scatter/scatter.py. Is my version of torch_scatter wrong?

**Comment by rusty1s** [comment]
I see. You need to upgrade `torch-geometric` :)

**Comment by wangzeyu135798** [comment]
&nbsp; &nbsp;Thanks for your reply!
&nbsp; &nbsp;May be I need update torch_geometric. Under torch-geometric==1.6.0, the function self.propagate under torch.nn.MessagePassing is ok. While the torch_geometric of code I use now is torch_geometric==1.0.3 when this code was published. When I update torch-geometric from 1.0.3 to 1.6.0, there is another question about geometric. Error: torch_geometric.nn.Data has no attribute 'cat_dim'.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rusty1s/pytorch_scatter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 下午5:06
收件人:&nbsp;"rusty1s/pytorch_scatter"<pytorch_scatter@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rusty1s/pytorch_scatter] scatter_add (#174)





 
I see. You need to upgrade torch-geometric :)

**Comment by rusty1s** [comment]
Well, you can also use an earlier version of `torch-geometric` (if that project requires it), but you need to also install an earlier `torch-scatter` version. In that case, that would be `torch-scatter==1.4.0`.

**Comment by wangzeyu135798** [comment]
That's the key for me.
I use several devices in windows and linux system to install previous version of torch_scatter except the latest version 2.0.5. While it occur same error: Failed building wheel for torch-scatter. How to solve it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rusty1s/pytorch_scatter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 下午5:18
收件人:&nbsp;"rusty1s/pytorch_scatter"<pytorch_scatter@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rusty1s/pytorch_scatter] scatter_add (#174)





 
Well, you can also use an earlier version of torch-geometric (if that project requires it), but you need to also install an earlier torch-scatter version. In that case, that would be torch-scatter==1.4.0.
